import { StyleSheet } from "react-native";

export function buildOldSchoolStyles(scale: number) {
  const m = (v: number) => Math.round(v * scale * 100) / 100;
  return StyleSheet.create({
    card: {
      width: "100%",
      height: "100%",
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "transparent",
    },
    sheet: {
      width: "100%",
      maxHeight: "98%",
      aspectRatio: 2.5,
      backgroundColor: "#f9f6ec",
      borderRadius: m(7),
      borderWidth: m(1),
      borderColor: "#b8ad93",
      flexDirection: "row",
      overflow: "hidden",
    },
    main: {
      flex: 3.35,
      minWidth: 0,
      margin: m(3),
      marginRight: 0,
      borderWidth: m(1),
      borderColor: "rgba(28,26,23,0.25)",
      borderRadius: m(4),
      backgroundColor: "#fdfbf4",
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: m(7),
      paddingTop: m(5),
      paddingBottom: m(3),
      gap: m(5),
      borderBottomWidth: m(1),
      borderBottomColor: "rgba(255,255,255,0.35)",
    },
    badgeFallback: {
      width: m(16),
      height: m(16),
      borderRadius: m(8),
      alignItems: "center",
      justifyContent: "center",
    },
    badgeFallbackText: { fontSize: m(9), fontWeight: "900", color: "#ffffff" },
    clubName: {
      flex: 1,
      fontSize: m(13),
      fontWeight: "900",
      letterSpacing: m(1),
      color: "#ffffff",
    },
    seasonTag: {
      fontSize: m(7),
      fontWeight: "800",
      letterSpacing: m(1.2),
    },
    metaStrip: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: m(4),
      paddingVertical: m(3),
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: "rgba(28,26,23,0.2)",
    },
    metaItem: {
      fontSize: m(6),
      fontWeight: "700",
      letterSpacing: m(0.8),
      color: "#5c554a",
      textTransform: "uppercase",
    },
    metaDot: {
      fontSize: m(6),
      fontWeight: "900",
      color: "#b8ad93",
    },
    matchup: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      minHeight: 0,
      paddingHorizontal: m(6),
    },
    homeName: {
      fontSize: m(11),
      fontWeight: "800",
      letterSpacing: m(1.5),
      color: "#3c362c",
      textTransform: "uppercase",
    },
    versusWrap: {
      flexDirection: "row",
      alignItems: "center",
      marginVertical: m(2),
      gap: m(6),
    },
    versusRule: {
      width: m(22),
      height: m(1.5),
      backgroundColor: "#b8ad93",
    },
    versus: {
      fontSize: m(10),
      fontWeight: "900",
      letterSpacing: m(2),
      color: "#8b6b24",
    },
    awayName: {
      fontSize: m(21),
      lineHeight: m(24),
      fontWeight: "900",
      letterSpacing: m(0.5),
      color: "#1c1a17",
      textTransform: "uppercase",
      textAlign: "center",
    },
    seatPanel: {
      flexDirection: "row",
      flexWrap: "wrap",
      backgroundColor: "#211d18",
      paddingHorizontal: m(6),
      paddingVertical: m(4),
      gap: m(8),
      borderTopWidth: m(1),
      borderTopColor: "#b8ad93",
    },
    seatCell: { minWidth: m(40) },
    seatLabel: {
      fontSize: m(5),
      fontWeight: "800",
      letterSpacing: m(1),
      color: "#c9b06a",
    },
    seatValue: {
      fontSize: m(9),
      fontWeight: "900",
      letterSpacing: m(0.6),
      color: "#f5efdd",
    },
    infoArea: {
      flexDirection: "row",
      flexWrap: "wrap",
      paddingHorizontal: m(7),
      paddingTop: m(4),
      paddingBottom: m(5),
      gap: m(10),
    },
    infoCell: { maxWidth: "46%" },
    infoLabel: {
      fontSize: m(5),
      fontWeight: "800",
      letterSpacing: m(1),
      color: "#8b6b24",
    },
    infoValue: {
      fontSize: m(6.5),
      fontWeight: "700",
      color: "#1c1a17",
      marginTop: m(0.5),
    },
    footerBand: {
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: m(2.5),
    },
    footerText: {
      fontSize: m(6),
      fontWeight: "800",
      letterSpacing: m(1.6),
      color: "#ffffff",
    },
    perf: {
      width: 0,
      borderLeftWidth: m(1),
      borderStyle: "dashed",
      borderLeftColor: "#9a8f76",
    },
    notchTop: {
      position: "absolute",
      top: -m(5),
      right: -m(5),
      width: m(10),
      height: m(10),
      borderRadius: m(5),
      backgroundColor: "#e8e1cf",
      borderWidth: m(1),
      borderColor: "#b8ad93",
      zIndex: 2,
    },
    notchBottom: {
      position: "absolute",
      bottom: -m(5),
      right: -m(5),
      width: m(10),
      height: m(10),
      borderRadius: m(5),
      backgroundColor: "#e8e1cf",
      borderWidth: m(1),
      borderColor: "#b8ad93",
      zIndex: 2,
    },
    stub: {
      width: "24%",
      backgroundColor: "#f4efdf",
      marginLeft: m(3),
      marginBottom: m(3),
      marginTop: m(3),
      borderTopLeftRadius: m(4),
      borderBottomLeftRadius: m(4),
      alignItems: "center",
      overflow: "hidden",
    },
    stubBand: {
      alignSelf: "stretch",
      alignItems: "center",
      paddingVertical: m(2.5),
    },
    stubBandText: {
      fontSize: m(6),
      fontWeight: "900",
      letterSpacing: m(1.4),
      color: "#ffffff",
    },
    stubFixture: {
      alignItems: "center",
      paddingHorizontal: m(4),
      paddingTop: m(4),
    },
    stubTeams: {
      fontSize: m(7),
      fontWeight: "900",
      color: "#1c1a17",
      textAlign: "center",
      textTransform: "uppercase",
    },
    stubDate: {
      fontSize: m(5.5),
      fontWeight: "700",
      color: "#5c554a",
      marginTop: m(1),
      letterSpacing: m(0.4),
    },
    stubDivider: {
      alignSelf: "stretch",
      borderTopWidth: m(1),
      borderStyle: "dotted",
      borderTopColor: "#9a8f76",
      marginTop: m(4),
      marginHorizontal: m(5),
    },
    stubSeatBlock: {
      alignItems: "center",
      paddingTop: m(4),
      gap: m(2),
    },
    stubSeatLine: {
      fontSize: m(6.5),
      fontWeight: "900",
      color: "#1c1a17",
      letterSpacing: m(0.5),
    },
    stubQrFrame: {
      backgroundColor: "#ffffff",
      padding: m(2),
      borderWidth: m(1),
      borderColor: "#b8ad93",
      marginTop: m(4),
    },
    qrImage: { width: m(38), height: m(38) },
    stubAdmit: {
      fontSize: m(5),
      fontWeight: "800",
      letterSpacing: m(1.6),
      color: "#8b6b24",
      marginTop: m(3),
      marginBottom: m(4),
    },
  });
}
