export type ClubOption = {
  id: string;
  name: string;
  league: string;
  stadium: string;
  stadiumLocation: string;
  primary: string;
  secondary: string;
  palette?: string[];
  badge?: string;
};

// Fresh installs land in onboarding before anything renders with a club, so
// no real club is ever a silent default. This placeholder only keeps the
// pre-onboarding state valid and is never persisted after onboarding.
export const PLACEHOLDER_CLUB_ID = "placeholder-club";
export const PLACEHOLDER_CLUB: ClubOption = {
  id: PLACEHOLDER_CLUB_ID,
  name: "Your Club",
  league: "",
  stadium: "",
  stadiumLocation: "",
  primary: "#17453a",
  secondary: "#f5f1e8",
};

export const ENGLISH_LEAGUES = [
  { label: "Premier League" },
  { label: "Championship" },
  { label: "League One" },
  { label: "League Two" },
  { label: "National League" },
  { label: "Scottish Premiership" },
  { label: "Scottish Championship" },
  { label: "Scottish League One" },
  { label: "Scottish League Two" },
] as const;

export const CLUB_COLOURS: Record<string, [string, string]> = {
  "Aldershot Town": ["#e30613", "#ffffff"],
  Altrincham: ["#e30613", "#ffffff"],
  Barnet: ["#f58220", "#000000"],
  "Braintree Town": ["#003087", "#ffffff"],
  "Boston United": ["#f9d616", "#000000"],
  "Brackley Town": ["#0057b8", "#ffffff"],
  Eastleigh: ["#0057b8", "#ffffff"],
  "FC Halifax Town": ["#005eb8", "#ffffff"],
  "Forest Green Rovers": ["#00843d", "#ffffff"],
  Gateshead: ["#000000", "#ffffff"],
  "Hartlepool United": ["#00205b", "#ffffff"],
  Morecambe: ["#f15b2a", "#ffffff"],
  Rochdale: ["#0066b3", "#ffffff"],
  "Scunthorpe United": ["#003087", "#ffffff"],
  "Solihull Moors": ["#ffd100", "#000000"],
  "Southend United": ["#0057b8", "#ffffff"],
  "Sutton United": ["#ffff00", "#000000"],
  Tamworth: ["#e30613", "#ffffff"],
  Woking: ["#0066cc", "#ffffff"],
  "Yeovil Town": ["#00843d", "#ffffff"],
  Celtic: ["#00843d", "#ffffff"],
  Rangers: ["#005eb8", "#ffffff"],
  Aberdeen: ["#d71920", "#ffffff"],
  "Heart of Midlothian": ["#870034", "#ffffff"],
  Hibernian: ["#007a33", "#ffffff"],
  Dundee: ["#003b7a", "#ffffff"],
  "Dundee United": ["#f58220", "#000000"],
  Kilmarnock: ["#003087", "#ffd100"],
  Motherwell: ["#ffc72c", "#c8102e"],
  "St Johnstone": ["#005eb8", "#ffffff"],
  "St Mirren": ["#000000", "#ffffff"],
  "Ayr United": ["#ffffff", "#000000"],
  "Dunfermline Athletic": ["#000000", "#ffffff"],
  "Greenock Morton": ["#0066b3", "#ffffff"],
  Livingston: ["#ffd100", "#000000"],
  "Partick Thistle": ["#ffcc00", "#006633"],
  "Queen's Park": ["#000000", "#ffffff"],
  "Raith Rovers": ["#000000", "#ffffff"],
  "Alloa Athletic": ["#ffcc00", "#000000"],
  "Cove Rangers": ["#005eb8", "#ffffff"],
  "East Fife": ["#ffd100", "#000000"],
  Montrose: ["#003087", "#ffffff"],
  Peterhead: ["#0057b8", "#ffffff"],
  "Queen of the South": ["#003087", "#ffffff"],
  Clyde: ["#ff0000", "#ffffff"],
  Dumbarton: ["#0066cc", "#ffffff"],
  "Elgin City": ["#000000", "#ffffff"],
  "Forfar Athletic": ["#003087", "#ffffff"],
  "Stirling Albion": ["#003087", "#ffffff"],
  Stranraer: ["#0057b8", "#ffffff"],
};

export const EXTRA_CLUBS: ClubOption[] = [
  ["Aberdeen", "Scottish Premiership"],
  ["Celtic", "Scottish Premiership"],
  ["Dundee", "Scottish Premiership"],
  ["Dundee United", "Scottish Premiership"],
  ["Falkirk", "Scottish Premiership"],
  ["Heart of Midlothian", "Scottish Premiership"],
  ["Hibernian", "Scottish Premiership"],
  ["Kilmarnock", "Scottish Premiership"],
  ["Motherwell", "Scottish Premiership"],
  ["Rangers", "Scottish Premiership"],
  ["St Johnstone", "Scottish Premiership"],
  ["St Mirren", "Scottish Premiership"],
  ["Arbroath", "Scottish Championship"],
  ["Ayr United", "Scottish Championship"],
  ["Dunfermline Athletic", "Scottish Championship"],
  ["Greenock Morton", "Scottish Championship"],
  ["Inverness Caledonian Thistle", "Scottish Championship"],
  ["Livingston", "Scottish Championship"],
  ["Partick Thistle", "Scottish Championship"],
  ["Queen's Park", "Scottish Championship"],
  ["Raith Rovers", "Scottish Championship"],
  ["Stenhousemuir", "Scottish Championship"],
  ["Airdrieonians", "Scottish League One"],
  ["Alloa Athletic", "Scottish League One"],
  ["Cove Rangers", "Scottish League One"],
  ["East Fife", "Scottish League One"],
  ["East Kilbride", "Scottish League One"],
  ["Hamilton Academical", "Scottish League One"],
  ["Montrose", "Scottish League One"],
  ["Peterhead", "Scottish League One"],
  ["Queen of the South", "Scottish League One"],
  ["Ross County", "Scottish League One"],
  ["Annan Athletic", "Scottish League Two"],
  ["Clyde", "Scottish League Two"],
  ["Dumbarton", "Scottish League Two"],
  ["Edinburgh City", "Scottish League Two"],
  ["Elgin City", "Scottish League Two"],
  ["Forfar Athletic", "Scottish League Two"],
  ["Kelty Hearts", "Scottish League Two"],
  ["Stirling Albion", "Scottish League Two"],
  ["Stranraer", "Scottish League Two"],
  ["The Spartans", "Scottish League Two"],
  ["Aldershot Town", "National League"],
  ["Altrincham", "National League"],
  ["Barnet", "National League"],
  ["Braintree Town", "National League"],
  ["Boston United", "National League"],
  ["Brackley Town", "National League"],
  ["Eastleigh", "National League"],
  ["FC Halifax Town", "National League"],
  ["Forest Green Rovers", "National League"],
  ["Gateshead", "National League"],
  ["Hartlepool United", "National League"],
  ["Morecambe", "National League"],
  ["Rochdale", "National League"],
  ["Scunthorpe United", "National League"],
  ["Solihull Moors", "National League"],
  ["Southend United", "National League"],
  ["Sutton United", "National League"],
  ["Tamworth", "National League"],
  ["Woking", "National League"],
  ["Yeovil Town", "National League"],
].map(([name, league], index) => ({
  id: `scotland-${index}`,
  name,
  league,
  stadium: `${name} stadium`,
  stadiumLocation: "Scotland",
  primary: CLUB_COLOURS[name]?.[0] ?? "#174a91",
  secondary: CLUB_COLOURS[name]?.[1] ?? "#ffffff",
})) satisfies ClubOption[];
