import type { ClubOption } from "@/lib/clubCatalog";

export const CLUB_THEME: Record<string, [string, string]> = {
  "AFC Bournemouth": ["#DA291C", "#000000"],
  "Arsenal": ["#EF0107", "#FFFFFF"],
  "Aston Villa": ["#670E36", "#95BFE5"],
  "Brentford": ["#E30613", "#FFFFFF"],
  "Brighton & Hove Albion": ["#0057B8", "#FFFFFF"],
  "Chelsea": ["#034694", "#FFFFFF"],
  "Coventry City": ["#69B3E7", "#FFFFFF"],
  "Crystal Palace": ["#1B458F", "#C4122E"],
  "Everton": ["#003399", "#FFFFFF"],
  "Fulham": ["#000000", "#FFFFFF"],
  "Hull City": ["#F5A12D", "#000000"],
  "Ipswich Town": ["#0033A0", "#FFFFFF"],
  "Leeds United": ["#1D428A", "#FFCD00"],
  "Liverpool": ["#C8102E", "#FFFFFF"],
  "Manchester City": ["#6CABDD", "#FFFFFF"],
  "Manchester United": ["#DA291C", "#000000"],
  "Newcastle United": ["#000000", "#FFFFFF"],
  "Nottingham Forest": ["#DD0000", "#FFFFFF"],
  "Sunderland": ["#EB172B", "#FFFFFF"],
  "Tottenham Hotspur": ["#132257", "#FFFFFF"],

  "Birmingham City": ["#0000FF", "#FFFFFF"],
  "Blackburn Rovers": ["#009EE0", "#FFFFFF"],
  "Bolton Wanderers": ["#263C7E", "#FFFFFF"],
  "Bristol City": ["#E21A22", "#FFFFFF"],
  "Burnley": ["#6C1D45", "#99D6EA"],
  "Cardiff City": ["#0070B5", "#FFFFFF"],
  "Charlton Athletic": ["#D71920", "#FFFFFF"],
  "Derby County": ["#000000", "#FFFFFF"],
  "Lincoln City": ["#E30613", "#FFFFFF"],
  "Middlesbrough": ["#E32219", "#FFFFFF"],
  "Millwall": ["#001B50", "#FFFFFF"],
  "Norwich City": ["#FFF200", "#00A650"],
  "Portsmouth": ["#001489", "#FFFFFF"],
  "Preston North End": ["#002D72", "#FFFFFF"],
  "Queens Park Rangers": ["#005CAB", "#FFFFFF"],
  "Sheffield United": ["#EE2737", "#FFFFFF"],
  "Southampton": ["#D71920", "#FFFFFF"],
  "Stoke City": ["#E03A3E", "#FFFFFF"],
  "Swansea City": ["#000000", "#FFFFFF"],
  "Watford": ["#FBEE23", "#ED2127"],
  "West Bromwich Albion": ["#122F67", "#FFFFFF"],
  "West Ham United": ["#7A263A", "#1BB1E7"],
  "Wolverhampton Wanderers": ["#FDB913", "#231F20"],
  "Wrexham": ["#D71920", "#FFFFFF"],

  "AFC Wimbledon": ["#0000FF", "#FFD700"],
  "Barnsley": ["#E31B23", "#FFFFFF"],
  "Blackpool": ["#F68712", "#FFFFFF"],
  "Bradford City": ["#6A1D45", "#F4C430"],
  "Bromley": ["#FFFFFF", "#000000"],
  "Burton Albion": ["#FFCC00", "#000000"],
  "Cambridge United": ["#FFCC00", "#000000"],
  "Doncaster Rovers": ["#E30613", "#FFFFFF"],
  "Huddersfield Town": ["#0E63AD", "#FFFFFF"],
  "Leicester City": ["#003090", "#FDBE11"],
  "Leyton Orient": ["#E30613", "#FFFFFF"],
  "Luton Town": ["#F78F1E", "#002D62"],
  "Mansfield Town": ["#F7D117", "#003399"],
  "Milton Keynes Dons": ["#FFFFFF", "#000000"],
  "Notts County": ["#000000", "#FFFFFF"],
  "Oxford United": ["#F9E300", "#002147"],
  "Peterborough United": ["#0054A6", "#FFFFFF"],
  "Plymouth Argyle": ["#004F3D", "#FFFFFF"],
  "Reading": ["#0046AD", "#FFFFFF"],
  "Sheffield Wednesday": ["#0054A6", "#FFFFFF"],
  "Stevenage": ["#E31B23", "#FFFFFF"],
  "Stockport County": ["#0054A6", "#FFFFFF"],
  "Wigan Athletic": ["#0054A6", "#FFFFFF"],
  "Wycombe Wanderers": ["#0033A0", "#87CEEB"],

  "Accrington Stanley": ["#E30613", "#FFFFFF"],
  "Barnet": ["#F5A623", "#000000"],
  "Bristol Rovers": ["#0054A6", "#FFFFFF"],
  "Cheltenham Town": ["#E30613", "#FFFFFF"],
  "Chesterfield": ["#0054A6", "#FFFFFF"],
  "Colchester United": ["#0054A6", "#FFFFFF"],
  "Crawley Town": ["#E30613", "#FFFFFF"],
  "Crewe Alexandra": ["#E30613", "#FFFFFF"],
  "Exeter City": ["#E30613", "#FFFFFF"],
  "Fleetwood Town": ["#E30613", "#FFFFFF"],
  "Gillingham": ["#0054A6", "#FFFFFF"],
  "Grimsby Town": ["#000000", "#FFFFFF"],
  "Newport County": ["#F58220", "#000000"],
  "Northampton Town": ["#7A263A", "#FFFFFF"],
  "Oldham Athletic": ["#0054A6", "#FFFFFF"],
  "Port Vale": ["#000000", "#FFFFFF"],
  "Rochdale": ["#0054A6", "#FFFFFF"],
  "Rotherham United": ["#E30613", "#FFFFFF"],
  "Salford City": ["#E30613", "#FFFFFF"],
  "Shrewsbury Town": ["#0054A6", "#F5C400"],
  "Swindon Town": ["#E30613", "#FFFFFF"],
  "Tranmere Rovers": ["#FFFFFF", "#0054A6"],
  "Walsall": ["#E30613", "#FFFFFF"],
  "York City": ["#E30613", "#FFFFFF"],
};

export const CLUBS_92: ClubOption[] = [
  ...[
    "AFC Bournemouth",
    "Arsenal",
    "Aston Villa",
    "Brentford",
    "Brighton & Hove Albion",
    "Chelsea",
    "Coventry City",
    "Crystal Palace",
    "Everton",
    "Fulham",
    "Hull City",
    "Ipswich Town",
    "Leeds United",
    "Liverpool",
    "Manchester City",
    "Manchester United",
    "Newcastle United",
    "Nottingham Forest",
    "Sunderland",
    "Tottenham Hotspur",
  ].map((name, index) => ({
    id: `pl-${index}-${name}`,
    name,
    league: "Premier League",
    stadium: `${name} stadium`,
    stadiumLocation: "England",
    primary: CLUB_THEME[name]?.[0] ?? "#174a91",
    secondary: CLUB_THEME[name]?.[1] ?? "#ffffff",
  })),

  ...[
    "Birmingham City",
    "Blackburn Rovers",
    "Bolton Wanderers",
    "Bristol City",
    "Burnley",
    "Cardiff City",
    "Charlton Athletic",
    "Derby County",
    "Lincoln City",
    "Middlesbrough",
    "Millwall",
    "Norwich City",
    "Portsmouth",
    "Preston North End",
    "Queens Park Rangers",
    "Sheffield United",
    "Southampton",
    "Stoke City",
    "Swansea City",
    "Watford",
    "West Bromwich Albion",
    "West Ham United",
    "Wolverhampton Wanderers",
    "Wrexham",
  ].map((name, index) => ({
    id: `ch-${index}-${name}`,
    name,
    league: "Championship",
    stadium: `${name} stadium`,
    stadiumLocation: "England",
    primary: CLUB_THEME[name]?.[0] ?? "#174a91",
    secondary: CLUB_THEME[name]?.[1] ?? "#ffffff",
  })),

  ...[
    "AFC Wimbledon",
    "Barnsley",
    "Blackpool",
    "Bradford City",
    "Bromley",
    "Burton Albion",
    "Cambridge United",
    "Doncaster Rovers",
    "Huddersfield Town",
    "Leicester City",
    "Leyton Orient",
    "Luton Town",
    "Mansfield Town",
    "Milton Keynes Dons",
    "Notts County",
    "Oxford United",
    "Peterborough United",
    "Plymouth Argyle",
    "Reading",
    "Sheffield Wednesday",
    "Stevenage",
    "Stockport County",
    "Wigan Athletic",
    "Wycombe Wanderers",
  ].map((name, index) => ({
    id: `l1-${index}-${name}`,
    name,
    league: "League One",
    stadium: `${name} stadium`,
    stadiumLocation: "England",
    primary: CLUB_THEME[name]?.[0] ?? "#174a91",
    secondary: CLUB_THEME[name]?.[1] ?? "#ffffff",
  })),

  ...[
    "Accrington Stanley",
    "Barnet",
    "Bristol Rovers",
    "Cheltenham Town",
    "Chesterfield",
    "Colchester United",
    "Crawley Town",
    "Crewe Alexandra",
    "Exeter City",
    "Fleetwood Town",
    "Gillingham",
    "Grimsby Town",
    "Newport County",
    "Northampton Town",
    "Oldham Athletic",
    "Port Vale",
    "Rochdale",
    "Rotherham United",
    "Salford City",
    "Shrewsbury Town",
    "Swindon Town",
    "Tranmere Rovers",
    "Walsall",
    "York City",
  ].map((name, index) => ({
    id: `l2-${index}-${name}`,
    name,
    league: "League Two",
    stadium: `${name} stadium`,
    stadiumLocation: "England",
    primary: CLUB_THEME[name]?.[0] ?? "#174a91",
    secondary: CLUB_THEME[name]?.[1] ?? "#ffffff",
  })),
];

