export type FootballGround = {
  id: string;
  stadium: string;
  club: string;
  league: string;
  address: string;
  latitude: number;
  longitude: number;
  fromDate?: string;
  toDate?: string;
};

export const FOOTBALL_GROUNDS: FootballGround[] = [
  // Premier League
  { id: "emirates", stadium: "Emirates Stadium", club: "Arsenal", league: "Premier League", address: "Queensland Road, London N7 9AJ", latitude: 51.5549, longitude: -0.1084, fromDate: "2006-07-01" },
  { id: "villa-park", stadium: "Villa Park", club: "Aston Villa", league: "Premier League", address: "Trinity Road, Birmingham B6 6HE", latitude: 52.5092, longitude: -1.8847 },
  { id: "vitality", stadium: "Vitality Stadium", club: "Bournemouth", league: "Premier League", address: "Dean Court, Bournemouth BH7 7AF", latitude: 50.7352, longitude: -1.8389 },
  { id: "gtech", stadium: "Gtech Community Stadium", club: "Brentford", league: "Premier League", address: "166 Lionel Road North, Brentford TW8 0RU", latitude: 51.4908, longitude: -0.2886, fromDate: "2020-09-01" },
  { id: "amex", stadium: "American Express Stadium", club: "Brighton & Hove Albion", league: "Premier League", address: "Village Way, Falmer BN1 9BL", latitude: 50.8611, longitude: -0.0804, fromDate: "2011-08-01" },
  { id: "turf-moor", stadium: "Turf Moor", club: "Burnley", league: "Championship", address: "Harry Potts Way, Burnley BB10 4BX", latitude: 53.7891, longitude: -2.23 },
  { id: "stamford-bridge", stadium: "Stamford Bridge", club: "Chelsea", league: "Premier League", address: "Fulham Road, London SW6 1HS", latitude: 51.4817, longitude: -0.1911 },
  { id: "selhurst-park", stadium: "Selhurst Park", club: "Crystal Palace", league: "Premier League", address: "Holmesdale Road, London SE25 6PU", latitude: 51.3983, longitude: -0.0855 },
  { id: "hill-dickinson", stadium: "Hill Dickinson Stadium", club: "Everton", league: "Premier League", address: "Bramley-Moore Dock, Liverpool L3 0BJ", latitude: 53.4249, longitude: -3.00271, fromDate: "2025-07-01" },
  { id: "craven-cottage", stadium: "Craven Cottage", club: "Fulham", league: "Premier League", address: "Stevenage Road, London SW6 9HH", latitude: 51.4752, longitude: -0.2216 },
  { id: "elland-road", stadium: "Elland Road", club: "Leeds United", league: "Premier League", address: "Elland Road, Beeston, Leeds LS11 5DJ", latitude: 53.7777, longitude: -1.5722 },
  { id: "anfield", stadium: "Anfield", club: "Liverpool", league: "Premier League", address: "Anfield Road, Liverpool L4 0SW", latitude: 53.4308, longitude: -2.9608 },
  { id: "etihad", stadium: "Etihad Stadium", club: "Manchester City", league: "Premier League", address: "Rowsley Street, Manchester M11 3FF", latitude: 53.4831, longitude: -2.2004, fromDate: "2003-08-01" },
  { id: "old-trafford", stadium: "Old Trafford", club: "Manchester United", league: "Premier League", address: "Sir Matt Busby Way, Manchester M16 0RA", latitude: 53.4631, longitude: -2.2913 },
  { id: "st-james-park", stadium: "St James' Park", club: "Newcastle United", league: "Premier League", address: "St James' Park, Newcastle NE1 4ST", latitude: 54.9756, longitude: -1.6217 },
  { id: "city-ground", stadium: "The City Ground", club: "Nottingham Forest", league: "Premier League", address: "Pavilion Road, West Bridgford, Nottingham NG2 5FJ", latitude: 52.94, longitude: -1.131 },
  { id: "stadium-of-light", stadium: "Stadium of Light", club: "Sunderland", league: "Premier League", address: "Frenchman's Way, Sunderland SR5 1SU", latitude: 54.9147, longitude: -1.3885, fromDate: "1997-08-01" },
  { id: "spurs-stadium", stadium: "Tottenham Hotspur Stadium", club: "Tottenham Hotspur", league: "Premier League", address: "748 High Road, London N17 0AP", latitude: 51.6043, longitude: -0.0662, fromDate: "2019-04-03" },
  { id: "london-stadium", stadium: "London Stadium", club: "West Ham United", league: "Championship", address: "Marshgate Lane, London E15 2PJ", latitude: 51.5383, longitude: -0.0166, fromDate: "2016-08-01" },
  { id: "molineux", stadium: "Molineux", club: "Wolverhampton Wanderers", league: "Championship", address: "Waterloo Road, Wolverhampton WV1 4QR", latitude: 52.487, longitude: -2.1304 },

  // Championship
  { id: "st-andrews", stadium: "St Andrew's", club: "Birmingham City", league: "Championship", address: "Bordesley Green, Birmingham B9 4NH", latitude: 52.4554, longitude: -1.8685 },
  { id: "ewood-park", stadium: "Ewood Park", club: "Blackburn Rovers", league: "Championship", address: "Nuttall Street, Blackburn BB2 4JF", latitude: 53.7282, longitude: -2.4851 },
  { id: "ashton-gate", stadium: "Ashton Gate", club: "Bristol City", league: "Championship", address: "Ashton Road, Bristol BS3 2EJ", latitude: 51.44, longitude: -2.6201 },
  { id: "the-valley", stadium: "The Valley", club: "Charlton Athletic", league: "Championship", address: "Floyd Road, London SE7 8BL", latitude: 51.4866, longitude: 0.0374 },
  { id: "cbs-arena", stadium: "Coventry Building Society Arena", club: "Coventry City", league: "Premier League", address: "Judds Lane, Coventry CV6 6AQ", latitude: 52.4483, longitude: -1.4978, fromDate: "2005-08-01" },
  { id: "pride-park", stadium: "Pride Park", club: "Derby County", league: "Championship", address: "Pride Parkway, Derby DE24 8XL", latitude: 52.9148, longitude: -1.4473, fromDate: "1997-08-01" },
  { id: "mkm-stadium", stadium: "MKM Stadium", club: "Hull City", league: "Premier League", address: "The Circle, Hull HU3 6HU", latitude: 53.7466, longitude: -0.3684, fromDate: "2002-12-01" },
  { id: "portman-road", stadium: "Portman Road", club: "Ipswich Town", league: "Premier League", address: "Portman Road, Ipswich IP1 2BP", latitude: 52.0555, longitude: 1.1486 },
  { id: "king-power", stadium: "King Power Stadium", club: "Leicester City", league: "League One", address: "Filbert Way, Leicester LE2 7FL", latitude: 52.6204, longitude: -1.1424, fromDate: "2002-08-01" },
  { id: "riverside", stadium: "Riverside Stadium", club: "Middlesbrough", league: "Championship", address: "The Riverside, Middlesbrough TS3 6RS", latitude: 54.5778, longitude: -1.2156, fromDate: "1995-08-01" },
  { id: "the-den", stadium: "The Den", club: "Millwall", league: "Championship", address: "Zampa Road, London SE16 3LN", latitude: 51.4875, longitude: -0.0375 },
  { id: "carrow-road", stadium: "Carrow Road", club: "Norwich City", league: "Championship", address: "Carrow Road, Norwich NR1 1JE", latitude: 52.6219, longitude: 1.3082 },
  { id: "kassam", stadium: "Kassam Stadium", club: "Oxford United", league: "League One", address: " Grenoble Road, Oxford OX4 4XP", latitude: 51.7097, longitude: -1.1904 },
  { id: "fratton-park", stadium: "Fratton Park", club: "Portsmouth", league: "Championship", address: "Frogmore Road, Portsmouth PO4 8RA", latitude: 50.7963, longitude: -1.0649 },
  { id: "deepdale", stadium: "Deepdale", club: "Preston North End", league: "Championship", address: "Sir Tom Finney Way, Preston PR1 6RU", latitude: 53.7630, longitude: -2.6803 },
  { id: "loftus-road", stadium: "Loftus Road", club: "Queens Park Rangers", league: "Championship", address: "South Africa Road, London W12 7PA", latitude: 51.5101, longitude: -0.2324 },
  { id: "bramall-lane", stadium: "Bramall Lane", club: "Sheffield United", league: "Championship", address: "Bramall Lane, Sheffield S2 4SU", latitude: 53.3704, longitude: -1.4715 },
  { id: "hillsborough", stadium: "Hillsborough", club: "Sheffield Wednesday", league: "League One", address: "Hillsborough, Sheffield S6 1SW", latitude: 53.4115, longitude: -1.5005 },
  { id: "st-marys", stadium: "St Mary's Stadium", club: "Southampton", league: "Championship", address: "Britannia Road, Southampton SO14 5FP", latitude: 50.9058, longitude: -1.3903, fromDate: "2001-08-01" },
  { id: "bet365", stadium: "bet365 Stadium", club: "Stoke City", league: "Championship", address: "Stanley Matthews Way, Stoke-on-Trent ST4 4EG", latitude: 53.006, longitude: -2.1784, fromDate: "1997-08-01" },
  { id: "swansea-com", stadium: "Swansea.com Stadium", club: "Swansea City", league: "Championship", address: "Landore, Swansea SA1 2PE", latitude: 51.6422, longitude: -3.9346, fromDate: "2005-07-23" },
  { id: "vicarage-road", stadium: "Vicarage Road", club: "Watford", league: "Championship", address: "Vicarage Road, Watford WD18 0ER", latitude: 51.65, longitude: -0.4017 },
  { id: "the-hawthorns", stadium: "The Hawthorns", club: "West Bromwich Albion", league: "Championship", address: "Halfords Lane, West Bromwich B71 4LF", latitude: 52.5122, longitude: -2.0001 },
  { id: "racecourse", stadium: "Racecourse Ground", club: "Wrexham", league: "Championship", address: "Mold Road, Wrexham LL11 2AH", latitude: 53.0276, longitude: -2.992 },

  // League One
  { id: "plough-lane-afc", stadium: "Plough Lane", club: "AFC Wimbledon", league: "League One", address: "Plough Lane, London SW17 0NR", latitude: 51.4229, longitude: -0.1911 },
  { id: "oakwell", stadium: "Oakwell", club: "Barnsley", league: "League One", address: "Grove Street, Barnsley S71 1ET", latitude: 53.5523, longitude: -1.4696 },
  { id: "bloomfield-road", stadium: "Bloomfield Road", club: "Blackpool", league: "League One", address: "Seasiders Way, Blackpool FY1 6JJ", latitude: 53.8068, longitude: -3.1755 },
  { id: "university-of-bolton", stadium: "Toughsheet Community Stadium", club: "Bolton Wanderers", league: "Championship", address: "Burnden Way, Bolton BL6 6JW", latitude: 53.579, longitude: -2.5358, fromDate: "1997-08-01" },
  { id: "valley-parade", stadium: "Valley Parade", club: "Bradford City", league: "League One", address: "Valley Parade, Bradford BD8 7DY", latitude: 53.8038, longitude: -1.7597 },
  { id: "pirelli", stadium: "Pirelli Stadium", club: "Burton Albion", league: "League One", address: "Princess Way, Burton upon Trent DE13 0AR", latitude: 52.854, longitude: -1.63 },
  { id: "cardiff-city-stadium", stadium: "Cardiff City Stadium", club: "Cardiff City", league: "Championship", address: "Leckwith Road, Cardiff CF11 8AZ", latitude: 51.4748, longitude: -3.2017, fromDate: "2009-08-01" },
  { id: "eco-power", stadium: "Eco-Power Stadium", club: "Doncaster Rovers", league: "League One", address: "Stadium Way, Doncaster DN4 5JW", latitude: 53.5097, longitude: -1.1139 },
  { id: "st-james-park-exeter", stadium: "St James Park", club: "Exeter City", league: "League Two", address: "Old Tiverton Road, Exeter EX4 6PX", latitude: 50.73, longitude: -3.522 },
  { id: "highbury-fleetwood", stadium: "Highbury Stadium", club: "Fleetwood Town", league: "League One", address: "Park Avenue, Fleetwood FY7 6TX", latitude: 53.902, longitude: -3.015 },
  { id: "accu-stadium", stadium: "Accu Stadium", club: "Huddersfield Town", league: "League One", address: "Bradley Road, Huddersfield HD1 6PX", latitude: 53.6436, longitude: -1.8665 },
  { id: "brisbane-road", stadium: "Brisbane Road", club: "Leyton Orient", league: "League One", address: "Brisbane Road, London E10 5NF", latitude: 51.562, longitude: -0.006 },
  { id: "lner-stadium", stadium: "LNER Stadium", club: "Lincoln City", league: "Championship", address: "Sincil Bank, Lincoln LN5 8LD", latitude: 53.228, longitude: -0.536 },
  { id: "kenilworth-road", stadium: "Kenilworth Road", club: "Luton Town", league: "League One", address: "1 Maple Road, Luton LU4 8AW", latitude: 51.8886, longitude: -0.4349 },
  { id: "field-mill", stadium: "Field Mill", club: "Mansfield Town", league: "League One", address: "Quarry Lane, Mansfield NG18 5DA", latitude: 53.1404, longitude: -1.1866 },
  { id: "sixfields", stadium: "Sixfields Stadium", club: "Northampton Town", league: "League Two", address: "Walter Tull Way, Northampton NN5 5QA", latitude: 52.2561, longitude: -0.933 },
  { id: "london-road-peterborough", stadium: "London Road", club: "Peterborough United", league: "League One", address: "London Road, Peterborough PE2 8AL", latitude: 52.5694, longitude: -0.2226 },
  { id: "home-park", stadium: "Home Park", club: "Plymouth Argyle", league: "League One", address: "Mayflower Drive, Plymouth PL2 3DQ", latitude: 50.3873, longitude: -4.1553 },
  { id: "vale-park", stadium: "Vale Park", club: "Port Vale", league: "League Two", address: "Hamil Road, Burslem, Stoke-on-Trent ST6 1AW", latitude: 53.063, longitude: -2.192 },
  { id: "select-car-leasing", stadium: "Select Car Leasing Stadium", club: "Reading", league: "League One", address: "Madejski Park, Reading RG2 0FL", latitude: 51.42, longitude: -0.976, fromDate: "1998-08-01" },
  { id: "new-york-stadium", stadium: "New York Stadium", club: "Rotherham United", league: "League Two", address: "New York Way, Rotherham S60 1AH", latitude: 53.392, longitude: -1.347, fromDate: "2012-08-01" },
  { id: "lamex", stadium: "The Lamex Stadium", club: "Stevenage", league: "League One", address: "Broadhall Way, Stevenage SG2 8RH", latitude: 51.908, longitude: -0.213 },
  { id: "dw-stadium", stadium: "DW Stadium", club: "Wigan Athletic", league: "League One", address: "Loire Drive, Wigan WN5 0UZ", latitude: 53.545, longitude: -2.653, fromDate: "1999-08-01" },
  { id: "adams-park", stadium: "Adams Park", club: "Wycombe Wanderers", league: "League One", address: "Hillbottom Road, High Wycombe HP12 4HJ", latitude: 51.597, longitude: -0.707 },

  // League Two
  { id: "wham-stadium", stadium: "Wham Stadium", club: "Accrington Stanley", league: "League Two", address: "Livingston Road, Accrington BB5 0BX", latitude: 53.7545, longitude: -2.3696 },
  { id: "holker-street", stadium: "Holker Street", club: "Barrow", league: "National League", address: "Holker Street, Barrow-in-Furness LA14 5UA", latitude: 54.11, longitude: -3.227 },
  { id: "the-hive", stadium: "The Hive London", club: "Barnet", league: "League Two", address: "Camrose Avenue, Edgware HA8 6AG", latitude: 51.65, longitude: -0.277 },
  { id: "memorial-stadium", stadium: "Memorial Stadium", club: "Bristol Rovers", league: "League Two", address: "Filton Avenue, Bristol BS7 0BF", latitude: 51.497, longitude: -2.587 },
  { id: "hayes-lane", stadium: "Hayes Lane", club: "Bromley", league: "League One", address: "Hayes Lane, Bromley BR2 9EF", latitude: 51.3698, longitude: 0.0398 },
  { id: "abbey-stadium", stadium: "Abbey Stadium", club: "Cambridge United", league: "League One", address: "Newmarket Road, Cambridge CB5 8LN", latitude: 52.21, longitude: 0.148 },
  { id: "whaddon-road", stadium: "Whaddon Road", club: "Cheltenham Town", league: "League Two", address: "Albert Road, Cheltenham GL52 5NA", latitude: 51.894, longitude: -2.093 },
  { id: "chesterfield-stadium", stadium: "SMH Group Stadium", club: "Chesterfield", league: "League Two", address: "Sheffield Road, Chesterfield S41 8RX", latitude: 53.235, longitude: -1.443 },
  { id: "jobserve", stadium: "JobServe Community Stadium", club: "Colchester United", league: "League Two", address: "United Way, Colchester CO4 5UP", latitude: 51.885, longitude: 0.896 },
  { id: "broadfield", stadium: "Broadfield Stadium", club: "Crawley Town", league: "League Two", address: "Brighton Road, Crawley RH11 9RX", latitude: 51.109, longitude: -0.19 },
  { id: "alexandra-stadium", stadium: "Alexandra Stadium", club: "Crewe Alexandra", league: "League Two", address: "Gresty Road, Crewe CW2 6EB", latitude: 53.037, longitude: -2.466 },
  { id: "priestfield", stadium: "Priestfield Stadium", club: "Gillingham", league: "League Two", address: "Redfern Avenue, Gillingham ME7 4DD", latitude: 51.386, longitude: 0.533 },
  { id: "blundell-park", stadium: "Blundell Park", club: "Grimsby Town", league: "League Two", address: "Cleethorpes DN35 7PY", latitude: 53.568, longitude: -0.04 },
  { id: "envirovent", stadium: "EnviroVent Stadium", club: "Harrogate Town", league: "National League", address: "Wetherby Road, Harrogate HG2 7SA", latitude: 53.997, longitude: -1.516 },
  { id: "stadium-mk", stadium: "Stadium MK", club: "Milton Keynes Dons", league: "League One", address: "Denbigh North, Milton Keynes MK1 1ST", latitude: 52.028, longitude: -0.766 },
  { id: "rodney-parade", stadium: "Rodney Parade", club: "Newport County", league: "League Two", address: "Rodney Parade, Newport NP19 0UU", latitude: 51.583, longitude: -2.985 },
  { id: "meadow-lane", stadium: "Meadow Lane", club: "Notts County", league: "League One", address: "Meadow Lane, Nottingham NG2 3HJ", latitude: 52.95, longitude: -1.14 },
  { id: "boundary-park", stadium: "Boundary Park", club: "Oldham Athletic", league: "League Two", address: "Gamester Street, Oldham OL1 2BB", latitude: 53.575, longitude: -2.078 },
  { id: "peninsula-stadium", stadium: "Peninsula Stadium", club: "Salford City", league: "League Two", address: "Moor Lane, Salford M7 3PZ", latitude: 53.514, longitude: -2.313 },
  { id: "croud-meadow", stadium: "Croud Meadow", club: "Shrewsbury Town", league: "League Two", address: "Oteley Road, Shrewsbury SY2 6ST", latitude: 52.683, longitude: -2.72 },
  { id: "county-ground", stadium: "County Ground", club: "Swindon Town", league: "League Two", address: "County Road, Swindon SN1 2ED", latitude: 51.562, longitude: -1.772 },
  { id: "prenton-park", stadium: "Prenton Park", club: "Tranmere Rovers", league: "League Two", address: "Prenton Road West, Birkenhead CH42 9PY", latitude: 53.374, longitude: -3.04 },
  { id: "bescot", stadium: "Bescot Stadium", club: "Walsall", league: "League Two", address: "Bescot Crescent, Walsall WS1 4SA", latitude: 52.583, longitude: -2.058 },
  { id: "brunton-park", stadium: "Brunton Park", club: "Carlisle United", league: "League Two", address: "Warwick Road, Carlisle CA1 1LL", latitude: 54.895, longitude: -2.923 },

  // National League
  { id: "ebb-stadium", stadium: "EBB Stadium", club: "Aldershot Town", league: "National League", address: "High Street, Aldershot GU11 1TW", latitude: 51.248, longitude: -0.764 },
  { id: "moss-lane", stadium: "Moss Lane", club: "Altrincham", league: "National League", address: "Moss Lane, Altrincham WA15 8AP", latitude: 53.389, longitude: -2.354 },
  { id: "meadow-park-borehamwood", stadium: "Meadow Park", club: "Boreham Wood", league: "National League", address: "Broughinge Road, Borehamwood WD6 5AL", latitude: 51.664, longitude: -0.274 },
  { id: "jakemans", stadium: "Jakemans Community Stadium", club: "Boston United", league: "National League", address: "York Street, Boston PE21 6JN", latitude: 52.993, longitude: -0.034 },
  { id: "cressing-road", stadium: "Cressing Road", club: "Braintree Town", league: "National League", address: "Cressing Road, Braintree CM7 3PZ", latitude: 51.879, longitude: 0.556 },
  { id: "victory-park", stadium: "Victory Park", club: "Chorley", league: "National League", address: "Duke Street, Chorley PR7 3DU", latitude: 53.656, longitude: -2.497 },
  { id: "silverlake", stadium: "Silverlake Stadium", club: "Eastleigh", league: "National League", address: "Stoneham Lane, Eastleigh SO50 9HT", latitude: 50.968, longitude: -1.337 },
  { id: "kuflink", stadium: "Kuflink Stadium", club: "Ebbsfleet United", league: "National League", address: "Stonebridge Road, Northfleet, Gravesend DA11 9GN", latitude: 51.441, longitude: 0.331 },
  { id: "gateshead-is", stadium: "Gateshead International Stadium", club: "Gateshead", league: "National League", address: "Neilson Road, Gateshead NE10 0EF", latitude: 54.954, longitude: -1.588 },
  { id: "the-shay", stadium: "The Shay", club: "FC Halifax Town", league: "National League", address: "Shay Syke, Halifax HX1 2YS", latitude: 53.72, longitude: -1.869 },
  { id: "victoria-park-hartlepool", stadium: "Victoria Park", club: "Hartlepool United", league: "National League", address: "Clarence Road, Hartlepool TS24 8BZ", latitude: 54.692, longitude: -1.206 },
  { id: "york-road", stadium: "York Road", club: "Maidenhead United", league: "National League", address: "York Road, Maidenhead SL6 1SF", latitude: 51.518, longitude: -0.716 },
  { id: "mazuma", stadium: "Mazuma Stadium", club: "Morecambe", league: "National League", address: "Christie Way, Morecambe LA4 4TB", latitude: 54.069, longitude: -2.854 },
  { id: "new-lawn", stadium: "The New Lawn", club: "Forest Green Rovers", league: "National League", address: "Nailsworth, Stroud GL6 0FG", latitude: 51.696, longitude: -2.227 },
  { id: "crown-oil-arena", stadium: "Crown Oil Arena", club: "Rochdale", league: "League Two", address: "Sandy Lane, Rochdale OL11 5DR", latitude: 53.618, longitude: -2.166 },
  { id: "glanford-park", stadium: "Glanford Park", club: "Scunthorpe United", league: "National League", address: "Jack Brownword Road, Scunthorpe DN15 8TD", latitude: 53.583, longitude: -0.674 },
  { id: "armco-arena", stadium: "ARMCO Arena", club: "Solihull Moors", league: "National League", address: "Damson Park, Solihull B91 2PP", latitude: 52.414, longitude: -1.777 },
  { id: "roots-hall", stadium: "Roots Hall", club: "Southend United", league: "National League", address: "Victoria Avenue, Southend-on-Sea SS2 6NQ", latitude: 51.548, longitude: 0.7 },
  { id: "gander-green-lane", stadium: "Gander Green Lane", club: "Sutton United", league: "National League", address: "Gander Green Lane, Sutton SM1 2EY", latitude: 51.366, longitude: -0.197 },
  { id: "lamb-ground", stadium: "The Lamb Ground", club: "Tamworth", league: "National League", address: "Kettlebrook, Tamworth B77 1AA", latitude: 52.617, longitude: -1.683 },
  { id: "grosvenor-vale", stadium: "Grosvenor Vale", club: "Wealdstone", league: "National League", address: "Grosvenor Vale, Ruislip HA4 6JQ", latitude: 51.578, longitude: -0.394 },
  { id: "kingfield", stadium: "Kingfield Stadium", club: "Woking", league: "National League", address: "Kingfield Road, Woking GU22 9AA", latitude: 51.31, longitude: -0.563 },
  { id: "york-community", stadium: "York Community Stadium", club: "York City", league: "League Two", address: "Monks Cross, York YO32 9AF", latitude: 53.946, longitude: -1.062 },
  { id: "huish-park", stadium: "Huish Park", club: "Yeovil Town", league: "National League", address: "Lufton Way, Yeovil BA22 8YF", latitude: 50.941, longitude: -2.65 },
  { id: "truro-city-stadium", stadium: "Truro City Stadium", club: "Truro City", league: "National League", address: "Threemilestone, Truro TR4 9LF", latitude: 50.263, longitude: -5.08 },
  { id: "leasing-com-stadium", stadium: "The Leasing.com Stadium", club: "Macclesfield", league: "National League", address: "London Road, Macclesfield SK11 7SP", latitude: 53.261, longitude: -2.116 },

  // Scottish Premiership
  { id: "pittodrie", stadium: "Pittodrie Stadium", club: "Aberdeen", league: "Scottish Premiership", address: "Pittodrie Street, Aberdeen AB24 5QH", latitude: 57.159, longitude: -2.088 },
  { id: "celtic-park", stadium: "Celtic Park", club: "Celtic", league: "Scottish Premiership", address: "London Road, Glasgow G40 3RE", latitude: 55.8497, longitude: -4.2056 },
  { id: "dens-park", stadium: "Dens Park", club: "Dundee", league: "Scottish Premiership", address: "Sandeman Street, Dundee DD3 7JY", latitude: 56.47, longitude: -2.975 },
  { id: "tannadice", stadium: "Tannadice Park", club: "Dundee United", league: "Scottish Premiership", address: "Tannadice Street, Dundee DD3 7 JW", latitude: 56.473, longitude: -2.97 },
  { id: "falkirk-stadium", stadium: "The Falkirk Stadium", club: "Falkirk", league: "Scottish Premiership", address: "Westfield, Falkirk FK2 9HD", latitude: 56.004, longitude: -3.913 },
  { id: "easter-road", stadium: "Easter Road", club: "Hibernian", league: "Scottish Premiership", address: "Albany Street, Edinburgh EH7 5QG", latitude: 55.9617, longitude: -3.168 },
  { id: "rugby-park", stadium: "The BBSP Rugby Park", club: "Kilmarnock", league: "Scottish Premiership", address: "Rugby Park, Kilmarnock KA1 1HF", latitude: 55.609, longitude: -4.496 },
  { id: "almondvale", stadium: "Almondvale Stadium", club: "Livingston", league: "Scottish Championship", address: "Aldomastis Park, Livingston EH54 7DN", latitude: 55.882, longitude: -3.52 },
  { id: "fir-park", stadium: "Fir Park", club: "Motherwell", league: "Scottish Premiership", address: "Fir Park Street, Motherwell ML1 2QN", latitude: 55.784, longitude: -3.981 },
  { id: "ibrox", stadium: "Ibrox Stadium", club: "Rangers", league: "Scottish Premiership", address: "150 Edmiston Drive, Glasgow G51 2XD", latitude: 55.8283, longitude: -4.2109 },
  { id: "st-mirren-park", stadium: "St Mirren Park", club: "St Mirren", league: "Scottish Premiership", address: "Greenhill Road, Paisley PA3 1RU", latitude: 55.85, longitude: -4.421 },
  { id: "tynecastle", stadium: "Tynecastle Park", club: "Heart of Midlothian", league: "Scottish Premiership", address: "McLeod Street, Edinburgh EH11 2NL", latitude: 55.94, longitude: -3.235 },

  // Scottish Championship
  { id: "new-broomfield", stadium: "New Broomfield", club: "Airdrieonians", league: "Scottish League One", address: "Airdrie ML6 0NX", latitude: 55.869, longitude: -3.971 },
  { id: "gayfield", stadium: "Gayfield Park", club: "Arbroath", league: "Scottish Championship", address: "Gayfield, Arbroath DD11 1QB", latitude: 56.559, longitude: -2.574 },
  { id: "somerset-park", stadium: "Somerset Park", club: "Ayr United", league: "Scottish Championship", address: "Tryfield Place, Ayr KA8 9NB", latitude: 55.462, longitude: -4.629 },
  { id: "east-end-park", stadium: "East End Park", club: "Dunfermline Athletic", league: "Scottish Championship", address: "Halbeath Road, Dunfermline KY12 7RB", latitude: 56.199, longitude: -3.417 },
  { id: "cappielow", stadium: "Cappielow Park", club: "Greenock Morton", league: "Scottish Championship", address: "Greenock Road, Greenock PA15 2TY", latitude: 55.943, longitude: -4.72 },
  { id: "new-douglas-park", stadium: "New Douglas Park", club: "Hamilton Academical", league: "Scottish Championship", address: "Bothwell Road, Hamilton ML3 0FT", latitude: 55.777, longitude: -4.036 },
  { id: "firhill", stadium: "Firhill Stadium", club: "Partick Thistle", league: "Scottish Championship", address: "80 Firhill Road, Glasgow G20 7AL", latitude: 55.882, longitude: -4.269 },
  { id: "queens-park-hampden", stadium: "Hampden Park", club: "Queen's Park", league: "Scottish Championship", address: "Letherby Drive, Glasgow G42 9BA", latitude: 55.825, longitude: -4.251 },
  { id: "starks-park", stadium: "Stark's Park", club: "Raith Rovers", league: "Scottish Championship", address: "Princess Park, Kirkcaldy KY1 1SA", latitude: 56.172, longitude: -3.155 },
  { id: "global-energy", stadium: "Global Energy Stadium", club: "Ross County", league: "Scottish League One", address: "Victoria Park, Dingwall IV15 9UL", latitude: 57.595, longitude: -4.427 },

  // Scottish League One
  { id: "indodrill", stadium: "Indodrill Stadium", club: "Alloa Athletic", league: "Scottish League One", address: "Clackmannan Road, Alloa FK10 1RR", latitude: 56.116, longitude: -3.793 },
  { id: "galabank", stadium: "Galabank", club: "Annan Athletic", league: "Scottish League One", address: "Market Street, Annan DG12 6AG", latitude: 54.987, longitude: -3.26 },
  { id: "balmoral-stadium", stadium: "Balmoral Stadium", club: "Cove Rangers", league: "Scottish League One", address: "Calder Park, Aberdeen AB12 3GU", latitude: 57.13, longitude: -2.109 },
  { id: "ainslie-park", stadium: "Ainslie Park", club: "The Spartans", league: "Scottish League One", address: "94 Pilton Drive, Edinburgh EH4 4PH", latitude: 55.968, longitude: -3.245 },
  { id: "new-central-park", stadium: "New Central Park", club: "Kelty Hearts", league: "Scottish League Two", address: "New Central Park, Kelty KY4 0JR", latitude: 56.135, longitude: -3.394 },
  { id: "caledonian-stadium", stadium: "Caledonian Stadium", club: "Inverness Caledonian Thistle", league: "Scottish Championship", address: "Stadium Road, Inverness IV1 1FF", latitude: 57.483, longitude: -4.218 },
  { id: "loons-park", stadium: "Loons Park", club: "Montrose", league: "Scottish League One", address: "Lunan Street, Montrose DD10 8HU", latitude: 56.711, longitude: -2.462 },
  { id: "balmoor", stadium: "Balmoor Stadium", club: "Peterhead", league: "Scottish League One", address: "Balmoor Terrace, Peterhead AB42 1PX", latitude: 57.504, longitude: -1.777 },
  { id: "palmerston", stadium: "Palmerston Park", club: "Queen of the South", league: "Scottish League One", address: "Terregles Street, Dumfries DG2 9BA", latitude: 55.068, longitude: -3.608 },
  { id: "ochilview", stadium: "Ochilview Park", club: "Stenhousemuir", league: "Scottish Championship", address: "Main Street, Larbert FK5 3QU", latitude: 56.024, longitude: -3.809 },

  // Scottish League Two
  { id: "new-dundas-park", stadium: "New Dundas Park", club: "Bonnyrigg Rose", league: "Scottish League Two", address: "Bonnyrigg EH19 2HA", latitude: 55.874, longitude: -3.107 },
  { id: "broadwood", stadium: "Broadwood Stadium", club: "Clyde", league: "Scottish League Two", address: "Janefield Place, Cumbernauld G67 1AX", latitude: 55.952, longitude: -3.993 },
  { id: "dumbarton-football-stadium", stadium: "Dumbarton Football Stadium", club: "Dumbarton", league: "Scottish League Two", address: "Castle Road, Dumbarton G82 1JJ", latitude: 55.941, longitude: -4.562 },
  { id: "meadowbank", stadium: "Meadowbank Stadium", club: "Edinburgh City", league: "Scottish League Two", address: "London Road, Edinburgh EH7 6AD", latitude: 55.956, longitude: -3.166 },
  { id: "bayview", stadium: "Bayview Stadium", club: "East Fife", league: "Scottish League Two", address: "Harbour View, Methil KY8 3RW", latitude: 56.183, longitude: -3.009 },
  { id: "k-park", stadium: "K-Park Training Academy", club: "East Kilbride", league: "Scottish League One", address: "Calderglen Road, East Kilbride G75 0QZ", latitude: 55.764, longitude: -4.15 },
  { id: "borough-briggs", stadium: "Borough Briggs", club: "Elgin City", league: "Scottish League Two", address: " Borough Briggs Road, Elgin IV30 1LP", latitude: 57.612, longitude: -3.309 },
  { id: "station-park-forfar", stadium: "Station Park", club: "Forfar Athletic", league: "Scottish League Two", address: "Lochside Road, Forfar DD8 1BY", latitude: 56.645, longitude: -2.888 },
  { id: "stair-park", stadium: "Stair Park", club: "Stranraer", league: "Scottish League Two", address: "London Road, Stranraer DG9 8AS", latitude: 54.903, longitude: -5.025 },
  { id: "forthbank", stadium: "Forthbank Stadium", club: "Stirling Albion", league: "Scottish League Two", address: "Springkerse, Stirling FK7 7UJ", latitude: 56.106, longitude: -3.923 },

  // Historical grounds (clubs that moved — kept so visit history survives).
  // fromDate/toDate = inclusive window when the club played HOME games there (YYYY-MM-DD).
  { id: "highbury", stadium: "Highbury", club: "Arsenal", league: "Historical", address: "Avenue Road, London N5 1DP", latitude: 51.5549, longitude: -0.0958, toDate: "2006-06-30" },
  { id: "goodison-park", stadium: "Goodison Park", club: "Everton", league: "Historical", address: "Goodison Road, Liverpool L4 4EL", latitude: 53.4368, longitude: -2.9663, toDate: "2025-06-30" },
  { id: "white-hart-lane", stadium: "White Hart Lane", club: "Tottenham Hotspur", league: "Historical", address: "748 High Road, London N17 0AP", latitude: 51.604, longitude: -0.07, toDate: "2017-06-30" },
  { id: "wembley-spurs", stadium: "Wembley Stadium", club: "Tottenham Hotspur", league: "Historical", address: "Wembley, London HA9 0WS", latitude: 51.556, longitude: -0.2795, fromDate: "2017-07-01", toDate: "2019-04-02" },
  { id: "boleyn-ground", stadium: "Boleyn Ground", club: "West Ham United", league: "Historical", address: "Green Street, London E13 9AZ", latitude: 51.532, longitude: 0.034, toDate: "2016-06-30" },
  { id: "maine-road", stadium: "Maine Road", club: "Manchester City", league: "Historical", address: "Moss Side, Manchester M14 7SS", latitude: 53.47, longitude: -2.201, toDate: "2003-06-30" },
  { id: "filbert-street", stadium: "Filbert Street", club: "Leicester City", league: "Historical", address: "Filbert Street, Leicester LE2 7EE", latitude: 52.631, longitude: -1.135, toDate: "2002-06-30" },
  { id: "the-dell", stadium: "The Dell", club: "Southampton", league: "Historical", address: "Milton Road, Southampton SO15 2JR", latitude: 50.913, longitude: -1.408, toDate: "2001-06-30" },
  { id: "baseball-ground", stadium: "Baseball Ground", club: "Derby County", league: "Historical", address: "Normanton, Derby DE24 8LL", latitude: 52.9, longitude: -1.457, toDate: "1997-06-30" },
  { id: "highfield-road", stadium: "Highfield Road", club: "Coventry City", league: "Historical", address: "Kingfield Road, Coventry CV6 5AQ", latitude: 52.43, longitude: -1.48, toDate: "2005-06-30" },
  { id: "roker-park", stadium: "Roker Park", club: "Sunderland", league: "Historical", address: "Roker, Sunderland SR6 9PA", latitude: 54.916, longitude: -1.373, toDate: "1997-06-30" },
  { id: "griffin-park", stadium: "Griffin Park", club: "Brentford", league: "Historical", address: "Braemar Road, Brentford TW8 0NT", latitude: 51.508, longitude: -0.301, toDate: "2020-08-31" },
  { id: "boothferry-park", stadium: "Boothferry Park", club: "Hull City", league: "Historical", address: "Boothferry Road, Hull HU4 6EU", latitude: 53.733, longitude: -0.352, toDate: "2002-11-30" },
  { id: "elm-park", stadium: "Elm Park", club: "Reading", league: "Historical", address: "Elm Park, Reading RG30 4TR", latitude: 51.437, longitude: -0.972, toDate: "1998-06-30" },
  { id: "vetch-field", stadium: "Vetch Field", club: "Swansea City", league: "Historical", address: "Vetch Field, Swansea SA1 4SA", latitude: 51.618, longitude: -3.941, toDate: "2005-06-30" },
  { id: "ninian-park", stadium: "Ninian Park", club: "Cardiff City", league: "Historical", address: "Sloper Road, Cardiff CF11 8SX", latitude: 51.476, longitude: -3.211, toDate: "2009-07-31" },
  { id: "burnden-park", stadium: "Burnden Park", club: "Bolton Wanderers", league: "Historical", address: "Burnden, Bolton BL3 2HF", latitude: 53.58, longitude: -2.529, toDate: "1997-06-30" },
  { id: "ayresome-park", stadium: "Ayresome Park", club: "Middlesbrough", league: "Historical", address: "Ayresome Street, Middlesbrough TS1 4PS", latitude: 54.577, longitude: -1.238, toDate: "1995-06-30" },
  { id: "victoria-ground", stadium: "Victoria Ground", club: "Stoke City", league: "Historical", address: "Boothen, Stoke-on-Trent ST4 7PT", latitude: 53.003, longitude: -2.166, toDate: "1997-06-30" },
  { id: "springfield-park", stadium: "Springfield Park", club: "Wigan Athletic", league: "Historical", address: "Springfield Park, Wigan WN3 5JD", latitude: 53.564, longitude: -2.632, toDate: "1999-06-30" },
  { id: "millmoor", stadium: "Millmoor", club: "Rotherham United", league: "Historical", address: "Millmoor Lane, Rotherham S60 2HR", latitude: 53.388, longitude: -1.356, toDate: "2008-06-30" },
  { id: "don-valley", stadium: "Don Valley Stadium", club: "Rotherham United", league: "Historical", address: "Worksop Road, Sheffield S9 3TL", latitude: 53.409, longitude: -1.398, fromDate: "2008-07-01", toDate: "2012-07-31" },
  { id: "goldstone-ground", stadium: "Goldstone Ground", club: "Brighton & Hove Albion", league: "Historical", address: "Goldstone Villas, Hove BN3 3RD", latitude: 50.843, longitude: -0.245, toDate: "1997-04-30" },
  { id: "withdean", stadium: "Withdean Stadium", club: "Brighton & Hove Albion", league: "Historical", address: "Withdean Lane, Brighton BN1 5JD", latitude: 50.846, longitude: -0.155, fromDate: "1999-07-01", toDate: "2011-07-31" },
  { id: "plough-lane-old", stadium: "Plough Lane (old)", club: "Wimbledon", league: "Historical", address: "Plough Lane, London SW17 0BW", latitude: 51.425, longitude: -0.189 },
];
